### ISSUE TITLE
TLS Internal Error

### ISSUE THREAD

**Issue by joshcangit** [natesales/repo#2] opened 2023-10-04 07:24 UTC
Firefox: `SSL_ERROR_INTERNAL_ERROR_ALERT`
Chrome: `ERR_SSL_PROTOCOL_ERROR`
cURL:
```
curl: (35) error:0A000438:SSL routines::tlsv1 alert internal error
```

apt update:
```
Ign:1 https://repo.natesales.net/apt  InRelease     
Ign:1 https://repo.natesales.net/apt  InRelease     
Ign:1 https://repo.natesales.net/apt  InRelease    
Err:1 https://repo.natesales.net/apt  InRelease    
  Could not handshake: A TLS fatal alert has been received. [IP: 54.152.153.7 443]
Reading package lists... Done                      
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
W: Failed to fetch https://repo.natesales.net/apt/InRelease  Could not handshake: A TLS fatal alert has been received. [IP: 54.152.153.7 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by ArnaudFeld** [comment] 2023-10-21 19:27
Any News about that? @natesales

**Comment by natesales** [comment] 2023-10-22 06:00
Duplicate of #1, fixed in https://github.com/natesales/repo/commit/2571d08fd399ec64a4dfa23bf7afdfeeafaa8c10

**Closed by natesales** 2023-10-22 06:00 UTC
